swagger: '2.0'
info:
  version: '1.0'
  title: EPIC Mail
  description: >-
    As EPIC Andelans who work towards advancing human potential and giving back
    to the society, we wish to empower others by building a web app that helps
    people exchange messages/information over the internet.
  contact: {}
host: 'localhost:3000'
basePath: /api/v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /auth/login:
    post:
      description: A login post request made to EPIC Mail
      summary: 'http://localhost:6000/api/v1/auth/login'
      tags:
        - Misc
      operationId: AuthLoginPost
      deprecated: false
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: Content-Type
          in: header
          required: true
          type: string
          description: ''
        - name: email
          in: formData
          required: true
          type: string
          description: ''
        - name: password
          in: formData
          required: true
          type: string
          description: ''
      responses:
        '200':
          description: ''
          headers: {}
  /auth/signup:
    post:
      description: A user makes a signup post request to EPIC Mail
      summary: 'http://localhost:6000/api/v1/auth/signup'
      tags:
        - Misc
      operationId: AuthSignupPost
      deprecated: false
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: Content-Type
          in: header
          required: true
          type: string
          description: ''
        - name: email
          in: formData
          required: true
          type: string
          description: ''
        - name: firstName
          in: formData
          required: true
          type: string
          description: ''
        - name: lastName
          in: formData
          required: true
          type: string
          description: ''
        - name: password
          in: formData
          required: true
          type: string
          description: ''
        - name: username
          in: formData
          required: true
          type: string
          description: ''
        - name: recoveryEmail
          in: formData
          required: true
          type: string
          description: ''
      responses:
        '200':
          description: ''
          headers: {}
  /messages/2:
    delete:
      description: This is an endpoint that deletes a specific message
      summary: 'http://localhost:6000/api/v1/messages/2'
      tags:
        - Misc
      operationId: Messages2Delete
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: Content-Type
          in: header
          required: true
          type: string
          description: ''
        - name: Body
          in: body
          required: true
          description: ''
          schema:
            $ref: >-
              #/definitions/http%3A~1~1localhost%3A6000~1api~1v1~1messages~12Request
      responses:
        '200':
          description: ''
          headers: {}
    get:
      description: This is an endpoint that returns a specific message
      summary: 'http://localhost:6000/api/v1/messages/2'
      tags:
        - Misc
      operationId: Messages2Get
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: Content-Type
          in: header
          required: true
          type: string
          description: ''
      responses:
        '200':
          description: ''
          headers: {}
  /messages:
    get:
      description: This is an endpoint that returns all received messages
      summary: 'http://localhost:6000/api/v1/messages'
      tags:
        - Misc
      operationId: MessagesGet
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: Content-Type
          in: header
          required: true
          type: string
          description: ''
      responses:
        '200':
          description: ''
          headers: {}
  /messages/sent:
    get:
      description: This is an endpoint that returns all sent messages
      summary: 'http://localhost:6000/api/v1/messages/sent'
      tags:
        - Misc
      operationId: MessagesSentGet
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: Content-Type
          in: header
          required: true
          type: string
          description: ''
      responses:
        '200':
          description: ''
          headers: {}
  /messages/unread:
    get:
      description: This is an endpoint that returns all unread messages
      summary: 'http://localhost:6000/api/v1/messages/unread'
      tags:
        - Misc
      operationId: MessagesUnreadGet
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: Content-Type
          in: header
          required: true
          type: string
          description: ''
      responses:
        '200':
          description: ''
          headers: {}
definitions:
  'http://localhost:6000/api/v1/messages/2Request':
    title: 'http://localhost:6000/api/v1/messages/2Request'
    example:
      email: sebastinocj@yahoo.com
      password: klue
    type: object
    properties:
      email:
        type: string
      password:
        type: string
    required:
      - email
      - password
tags:
  - name: Misc
    description: ''
